spring:
  application:
    name: spring-sidecar
server:
  port: 8210
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:  # 健康检查
      enabled: true

#####################################################################################################
# 异构微服务的配置， port 代表异构微服务的端口；health-uri 代表异构微服务的操作链接地址
sidecar:
  port: 8205
  health-uri: http://localhost:8205/health.json     #此处为非java服务端的一个接口地址，返回必须为 {"status": "UP"}，用着eureka监听
#####################################################################################################
